import Head from 'next/head';
import { MoviesList } from '@/features';
import { results } from '@/utils';

export default function Home({ movies }) {
  return (
    <>
      <Head>
        <title>Next MDB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MoviesList movies={movies} />
      </main>
    </>
  );
}

export const getStaticProps = () => {
  return {
    props: { movies: results },
  };
};
